OpenGpxTracker/GPXFilesTableViewController.swift

Add logic in -tableView:canEditRowAtIndexPath: for swiping and
implement -tableView:shouldHighlightRowAtIndexPath: for tapping.

Prevent editing for "empty list"-placeholder row

---

OpenGpxTracker/Info.plist

Addresses enhancement https://github.com/merlos/iOS-Open-GPX-Tracker/issues/17. It's just one commit, adding Info.plist key to share Documents/ directory, where .gpx files are
stored.
It works out of the box with the app's current file persistency model. Has to be tested on-device (not Simulator).
It's handy because traces can be moved off the device w/o going through email, can be renamed, moved between devices, or quickly deleted.
When the file list controller is open and you make changes in iTunes, they are not picked up immediately, but that trade off seems worth the benefit. When closing the file list and reopening, all changes from iTunes are immediately reflected.

Enable iTunes File Sharing

---

OpenGpxTracker.xcodeproj/project.pbxproj
OpenGpxTracker/CachedTileOverlay.swift
OpenGpxTracker/GPXActivityItemProvider.swift
OpenGpxTracker/GPXFilesTableViewController.swift
OpenGpxTracker/Info.plist
OpenGpxTracker/MapViewDelegate.swift
OpenGpxTracker/ViewController.swift

Hello! This PR accomplishes #46 in a simple manner, adding a button to the Files Table. One could also go further and wrap all of the actions in the `UIAlertController` in `UIActivity`s and only use the `UIActivityViewController` to save taps.
This PR is one of two options, I've also created a PR (#53) that instead adds a Share button onto the main `ViewController`

Share from Files Table

---

OpenGpxTracker/GPXFilesTableViewController.swift
OpenGpxTracker/GPXMapView.swift
OpenGpxTracker/Info.plist
OpenGpxTracker/ViewController.swift

this should fix issue #57 , but has another issue where
```Warning: Attempt to present <UIActivityViewController: 0x104b2ca00> on <OpenGpxTracker.GPXFilesTableViewController: 0x1180f7d40> while a presentation is in progress!``` occurs when using the menu another time when dismissing it the first time.
issue #43 (for email) seems to also include the same "while a presentation is in progress" error

Fix for share button crash

---

OpenGpxTracker-Watch Extension/InterfaceController.swift

Closes #77. 
Once the Apple Watch Extension was started, it was requesting the location all the time independently of being tracking or not. 
To fix the issue I just moved the logic of `startUpdatingLocation` and `stopUpdatingLocation` to `didActivate` and `didDeactivate` respectively. 
`applicationDidBecomeActive()` and `didEnterBackground()` were never called, so were removed.
@vincentneo, does the watch extension create any temporary files? `applicationWillTerminate`  calls `GPXFileManager.removeTemporaryFiles()`, but `applicationWillTerminate` is never run. Shall we remove it or move to another place?
Thanks!

Fix battery consumption in Apple Watch

---

OpenGpxTracker-Watch Extension/GPXFileTableInterfaceController.swift
OpenGpxTracker/AppDelegate.swift
OpenGpxTracker/GPXFilesTableViewController.swift
OpenGpxTracker/ViewController.swift

This fixes #91, and fixes https://github.com/merlos/iOS-Open-GPX-Tracker/issues/78#issuecomment-471555681
The `WCSessionDelegate` is also moved from `ViewController` to `AppDelegate`

Auto reload table view when file received

---

OpenGpxTracker/AboutViewController.swift
OpenGpxTracker/about.html

`UIWebView` is deprecated since iOS 12. Since the minimum requirement was already iOS 8, `WKWebView` should be used instead, for the about view.
Also, I have fixed the `&apm;` thing in `about.html`

Migration to WebKit

---

OpenGpxTracker/GPXWaypoint+MKAnnotation.swift
OpenGpxTracker/MapViewDelegate.swift
OpenGpxTracker/ViewController.swift

This pull request allows elevation values to be logged in waypoint, when generating the waypoint using the add pin button. This is to partially resolve issue #102.
Possible scenario: 
- Only when adding pin using pin button.
- If waypoint with elevation is moved on map, elevation is removed, as it is irrelevant
- Waypoints added through other means will not have elevation value
- Editing of waypoint name should not remove elevation value

Include elevation during waypoint generation, when possible

---

OpenGpxTracker/GPXFilesTableViewController.swift
OpenGpxTracker/ViewController.swift

For a long time, I have always felt that when loading, or using the share button on map, with large files can be slow, and that it isn't represented by anything, just freezing in the process.
For this pull request, the following is added:
1. When share button is tapped, it is animated to a spinning activity indicator, replacing the button, and the button will appear after its done
2. When loading a file from table view, an alert with a spinning activity indicator and "Loading GPX File..." is shown to let user know work is being done.
3. Fixes iPad popup presentation view placement issues from quite a while ago, where the UI placement is still off.
I believe that this would improve the user experience as when the app freezes, the user can't really tell if its doing something or not, and …

UI Enhancements

---

OpenGpxTracker/GPXFileManager.swift

Bug described in [comment #65 by @wallstudios](https://github.com/merlos/iOS-Open-GPX-Tracker/issues/65#issuecomment-513606304).
Basically, the file extension **.gpx** would show in the file manager, but not **.GPX**
That should not be expected behaviour, and this should fix the issue, but not #65 as a whole.

Fixes uppercase file extension bug

---

OpenGpxTracker.xcodeproj/project.pbxproj

Don't see why this project would have an organization name.
New files created, will now not contain the copyright info, if this pull request is merged.

Removal of organization name

---

OpenGpxTracker/about.html

Well, almost everything's prep up with dark mode support, except for the about page.
This brings just that.

About page's dark mode support

---

OpenGpxTracker/MapViewDelegate.swift

Fixes the glitch between polyline overlay and Apple maps rail line.
Apparently, its due to how it renders polyline as vectors than bitmap. `shouldRasterize` forces it to go back to pre iOS 13 style.
Apple docs: [shouldRasterize](https://developer.apple.com/documentation/mapkit/mkoverlaypathrenderer/3088846-shouldrasterize)

Fix for polyline glitch

---

OpenGpxTracker/GPXMapView.swift
OpenGpxTracker/GPXTileServer.swift
OpenGpxTracker/MapViewDelegate.swift
OpenGpxTracker/PreferencesTableViewController.swift
Podfile
Podfile.lock
Pods/Manifest.lock
Pods/MapCache/MapCache/Classes/DiskCache/DiskCache.swift
Pods/MapCache/MapCache/Classes/DiskCache/FileManager+DiskCache.swift
Pods/MapCache/MapCache/Classes/DiskCache/MD5.swift
Pods/MapCache/MapCache/Classes/DiskCache/URL+DiskCache.swift
Pods/MapCache/MapCache/Classes/MKMapView+MapCache.swift
Pods/MapCache/MapCache/Classes/MapCache.swift
Pods/MapCache/MapCache/Classes/MapCacheConfig.swift
Pods/MapCache/README.md
Pods/Pods.xcodeproj/project.pbxproj
Pods/Target Support Files/MapCache/MapCache-Info.plist

Fixes issues with tiles in ios13 and cache size calculation

---

OpenGpxTracker/GPXMapView.swift

This should hide the logo and "legal", when map is not Apple Maps. 
The issue with this, is that I do not know if it will be app store rejected...

Hide apple logo when map is third party

---

OpenGpxTracker/Info.plist

This should fix the issue #137 
@vincentneo  For me what happened is that after installing the app with the fix, with airdrop I still got the dialog box with the App store /  Download in files (the one posted on the bug thread), Then on Files app  the file had a white icon, I selected to open it with Open GPX tracker and after that it always opened GPX files with the app.
Now,  I cannot reproduce this anymore... if I remove the app and install again it automatically links the GPX files with Open GPX Tracker.
According to this thread https://forums.developer.apple.com/thread/118932, it was a bug in iOS13
In the iPad I could not reproduce the bug at all. The bug can only be reproduced  when you have more than one app that opens gpx files in the device.

Fixes open files with the app (#137)

---

OpenGpxTracker/GPXMapView.swift

Well, because I implemented force unwraps for a class that doesn't exist < iOS 12..., in #140.
Also, I didn't want to use #available, just to prevent a possible app crash in future, if Apple decides to rename them.

Fixes crash on > iOS 13 for hiding logo and text

---

OpenGpxTracker.xcodeproj/project.pbxproj
OpenGpxTracker/GPXFilesTableViewController.swift
OpenGpxTracker/UIColor+DarkMode.swift
OpenGpxTracker/ViewController.swift

I noticed that while the spinning indicator is shown, and if dark mode is switched, the spinner will not change colors.
This should fix it.

Better handling of color changes for dark mode

---

OpenGpxTracker.xcodeproj/project.pbxproj
OpenGpxTracker/DateField.swift
OpenGpxTracker/DateFieldButton.swift
OpenGpxTracker/DateFieldTypeView.swift
OpenGpxTracker/DatePatternButton.swift
OpenGpxTracker/DefaultDateFormat.swift
OpenGpxTracker/DefaultNameSetupViewController.swift
OpenGpxTracker/Preferences.swift
OpenGpxTracker/PreferencesTableViewController.swift
OpenGpxTracker/String+CountInstances.swift
OpenGpxTracker/UIColor+DarkMode.swift
OpenGpxTracker/UIColor+Keyboard.swift
OpenGpxTracker/UIInsetLabel.swift
OpenGpxTracker/ViewController.swift
OpenGpxTracker/de.lproj/Localizable.strings
OpenGpxTracker/en.lproj/Localizable.strings
OpenGpxTracker/es.lproj/Localizable.strings
OpenGpxTracker/uk.lproj/Localizable.strings
OpenGpxTracker/zh-Hans.lproj/Localizable.strings

close #146.
This pull request implements a UI that allows users to choose their own default file name based on their own requirements. I'm hoping that the UI is self explanatory and easy to understand.
Basically date/time syntax is wrapped by `{}`, instead of default date formatter formatting, as I believe that it will be easier for normal users to understand.
Keyboard has a bar with some date/time inputs, but can definitely be improved as it is currently very vague. (But idk what kind of view I should use)
Option to force use of english locale date as filename is also available, for when Locale language is not English. 
Overall it should work well for people that uses one of 5 presets or knows custom date formatting syntax for now in this pull request.

Implementation of custom default name preferences

---

OpenGpxTracker-Watch Extension/InterfaceController.swift
OpenGpxTracker/CoreDataHelper.swift

Fix #168.
Fixes an issue where the app will crash on launch.
Occurs after using any methods that involves `NSFetchRequestResult`, which is unavailable in iOS 9, but was not known as it wasn't flagged out by compiler when in development.
Tested to be able to recover from the launch crash loop, in simulated environment.

Fix pre iOS 9 Core Data related crashes

---

OpenGpxTracker/GPXMapView.swift
OpenGpxTracker/GPXTileServer.swift

Add another option, which is CARTO's 2x/retina tiles, as I mentioned in #188.
Personally find that Wikimedia tiles work better for this retina style as I experimented in Avenue, than the CARTO ones. Should I add Wikimedia tile support too?

Support for @2x/retina tiles (Carto only)

---

OpenGpxTracker/MapViewDelegate.swift

For #199. Tested to solve the iOS 14.5 glitching issues.
Might be able to close too, since I believe the crash issue has to do with other things about the app instead of the poly line.
Note: this pr will merge to `projectRefresh2021` branch.

Fix for glitchy polylines

---

OpenGpxTracker-Watch Extension/InterfaceController.swift
OpenGpxTracker/ViewController.swift

Fixed an issue (#193) where a location permissions warning alert controller was presented in all cases for a fresh install of the app.
The problem was that the app did not check if the location permissions were requested before, so even if the user was never presented with a prompt the warning case would trigger - meaning users would always be shown the permissions denied warning no matter what they chose.
The fix is to rely on the `CLLocationManagerDelegate` call back of `locationManagerDidChangeAuthorization(_ :)`
which is called both at initialization time of `CLLocationManager` and when permissions are changed.
The check at `appDidBecomeActive` time has been removed because the aforementioned delegate call accomplishes the same thing.
See below:
My first contribution here, please let …

Fix location permissions warning issue (closes #193)

---

OpenGpxTracker/GPXMapView.swift
OpenGpxTracker/ViewController.swift

Uses `MKCompassButton` introduced in iOS 11, rather than repositioning the map's built in compass view, via private methods, going forwards.

fix iOS 15 compass sizing issue

---

OpenGpxTracker/GPXFileManager.swift
OpenGpxTracker/Preferences.swift
OpenGpxTracker/PreferencesTableViewController.swift
OpenGpxTracker/en.lproj/Localizable.strings
OpenGpxTracker/ru.lproj/Localizable.strings

Hi!
I added an option for selecting custom output directory for gpx files. This can be local folder on your device or from a cloud service. Potentially, it should resolve #149.
I added translations for new labels only for English and Russian languages. @merlos what's the approach with other locales? Should I use Google Translate/Deepl or there is a different process?

Added new option for selecting custom output folder

---

OpenGpxTracker/GPXMapView.swift
OpenGpxTracker/GPXTileServer.swift

Adds OpenSeaMap tile server.
The tiles have a transparent background, so it was used the  `Mkview+MapCache.userCache(_, canReplaceMapContent)` functionality of added in https://github.com/merlos/MapCache/pull/43
Closes #187

Added OpenSeaMap tile server

---

OpenGpxTracker/GPXTileServer.swift
OpenGpxTracker/about.html
README.md

**Please check if the PR fulfills these requirements**
**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bugfix
**What is the current behavior?** (You can also link to an open issue here)
OpenStreetMap is written inconsistently across the code base:
1. "OpenStreetMap" (correct)
2. "OpenStreetMaps"
3. Open Street Map
4. Open Street Maps
**What is the new behavior (if this is a feature change)?**
Incorrect versions changed to "OpenStreetMap".
**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No
**Other information**:
* See the official home page for the correct wording: https://www.openstreetmap.org/.
* There are more occurrences of the typo in the dependency …

Fix typos in "OpenStreetMap"
